# Generated by Django 5.2.9 on 2025-12-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("license_key", "product")},
        ),
    ]
